application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: django
  version: "1.4"
- name: jinja2
  version: latest

handlers:
- url: /
  script: main.app
  secure: always

- url: /registration
  script: main.app
  secure: always

- url: /launcher
  script: launcher.app
  secure: always

- url: /callback
  script: main.app
  secure: always

- url: /tweet
  script: tweet.app
  secure: always